[project]
name = "manim-with-manim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim>=0.19.1",
    "numpy>=2.3.5",
    "scikit-learn>=1.8.0",
]
